### ISSUE TITLE
安装时一直卡在推送镜像到镜像仓库

### ISSUE THREAD

**Issue by stepGitHub** [goodrain/rainbond-operator#76]
使用ui界面安装时一直卡在倒数第二步
推送镜像到远程仓库，能否手动改动仓库地址到阿里云，还是有其他解决方案
![image](https://user-images.githubusercontent.com/32606145/81797342-39999200-9541-11ea-81e2-0f4370e6bbd9.png)

**Comment by barnettZQG** [comment]
@stepGitHub 通过下述命令查看一下rainbond-operator的日志。
```
kubectl logs -f rainbond-operator-0 -n rbd-system operator
```
请把错误的日志提供给我们。

**Comment by stepGitHub** [comment]
![image](https://user-images.githubusercontent.com/32606145/81798037-1f13e880-9542-11ea-89c5-517b7f491af1.png)
谢谢

**Comment by barnettZQG** [comment]
抱歉，你提供的日志都是Info级别的正常日志且不完整。请过滤日志给出Error级别的日志行或提供完整日志。

**Comment by stepGitHub** [comment]
[operator.log](https://github.com/goodrain/rainbond-operator/files/4621509/operator.log)

**Comment by stepGitHub** [comment]
> 抱歉，你提供的日志都是Info级别的正常日志且不完整。请过滤日志给出Error级别的日志行或提供完整日志。

[operator.log](https://github.com/goodrain/rainbond-operator/files/4621512/operator.log)

**Comment by barnettZQG** [comment]
@stepGitHub 
建议使用以下方式重新安装:
```
helm install  rainbond-operator ./chart --set openapi.installMode=WithoutPackage --namespace=rbd-system
```

**Comment by stepGitHub** [comment]
![image](https://user-images.githubusercontent.com/32606145/82013033-d710d500-96ab-11ea-8a0c-6fe3c69cbe68.png)
mysql 启动不了
